import {
  // Core tables from schema.ts
  users,
  classrooms,
  studentClassrooms,
  classroomEnrollments,
  assignments,
  assignmentResources,
  submissions,
  proposals,
  proposalFeedback,
  proposalNotifications,
  storeItems,
  purchases,
  timeEntries,
  badges,
  studentBadges,
  challenges,
  challengeProgress,
  announcements,
  announcementReads,
  
  // Core types
  type User,
  type InsertUser,
  type Classroom,
  type InsertClassroom,
  type Assignment,
  type InsertAssignment,
  type AssignmentResource,
  type InsertAssignmentResource,
  type Submission,
  type InsertSubmission,
  type Proposal,
  type InsertProposal,
  type ProposalFeedback,
  type InsertProposalFeedback,
  type ProposalNotification,
  type InsertProposalNotification,
  type StoreItem,
  type InsertStoreItem,
  type Purchase,
  type InsertPurchase,
  type TimeEntry,
  type InsertTimeEntry,
  type Badge,
  type InsertBadge,
  type StudentBadge,
  type InsertStudentBadge,
  type Challenge,
  type InsertChallenge,
  type ChallengeProgress,
  type InsertChallengeProgress,
  type Announcement,
  type InsertAnnouncement,
  type AnnouncementRead,
  type InsertAnnouncementRead
} from "@shared/schema";

import { db } from "./db";
import { eq, desc, asc, and, or, ne, sql, count } from "drizzle-orm";